In [126]:
import torch

In [127]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ -68,  -72,   93, -100,   23,  -60])

In [128]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000]])

In [129]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [130]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [131]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [132]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [133]:
torch.arange(3, 10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [134]:
torch.linspace(2, 10, steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [135]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [136]:
logspace = torch.logspace(start=-10, end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [137]:
torch.eye(5) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [138]:
a = torch.tensor([[1, 2], [3, 4]])
torch.empty_like(a)

tensor([[0, 0],
        [0, 0]])

In [139]:
probabilities = torch.tensor([100.0,100.0,100.0]) # here we define the probability of happening of each index in this case 0,1,2 all three are equally likely to occur
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([2, 1, 1, 2, 2, 0, 2, 2, 0, 2])


In [140]:
probabilities = torch.tensor([10.0,90.0])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 0, 1, 1])


In [141]:
# concat
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [142]:
torch.tril(torch.ones(5, 5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [143]:
torch.triu(torch.ones(5, 5))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [145]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
print(out)
print(torch.exp(out))

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [146]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2) # 0 is swapped with 2
out.shape

torch.Size([4, 3, 2])

In [147]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [148]:
import torch.nn as nn

sample = torch.tensor([10.0, 10.0, 10.0])
linear = nn.Linear(3, 3, bias=False) # takes n inputs and spits out 3 outputs, after applying weights 
print(linear(sample))

tensor([ -7.6628,   2.1805, -12.0102], grad_fn=<SqueezeBackward4>)


In [149]:
import torch.nn as nn

sample = torch.tensor([1.0, 2.0, 3.0])
linear = nn.Linear(3, 5, bias=False)
'''
Output 1: 1.0 * w1 + 2.0 * w2 + 3.0 * w3
Output 2: 1.0 * w4 + 2.0 * w5 + 3.0 * w6
Output 3: 1.0 * w7 + 2.0 * w8 + 3.0 * w9
Output 4: 1.0 * w10 + 2.0 * w11 + 3.0 * w12
Output 5: 1.0 * w13 + 2.0 * w14 + 3.0 * w15
'''
print(linear(sample))

tensor([ 1.1964,  2.0531, -0.3151, -5.3420, -7.9935],
       grad_fn=<SqueezeBackward4>)


In [150]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# apply softmax
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [151]:
# how softmax is working

from math import exp


total = exp(1) + exp(2) + exp(3)
print([exp(1)/total, exp(2)/total, exp(3)/total])

[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]
