In [90]:
import torch

In [91]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ 60,   8,   4, -30,  95, -60])

In [92]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000]])

In [93]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [94]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [95]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [96]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [97]:
torch.arange(3, 10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [98]:
torch.linspace(2, 10, steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [99]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [100]:
logspace = torch.logspace(start=-10, end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [101]:
torch.eye(5) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [102]:
a = torch.tensor([[1, 2], [3, 4]])
torch.empty_like(a)

tensor([[0, 0],
        [0, 0]])