In [1]:
import torch

In [2]:
randint = torch.randint(-100,100,(6,))
randint

tensor([ -3, -19,  99,  82, -20,  27])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000]])

In [4]:
zeros = torch.zeros(2, 3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2, 3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
torch.arange(3, 10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [9]:
torch.linspace(2, 10, steps=5)

tensor([ 2.,  4.,  6.,  8., 10.])

In [10]:
torch.linspace(3, 10, steps=5)

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [11]:
logspace = torch.logspace(start=-10, end=10,steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [12]:
torch.eye(5) # identity matrix

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [13]:
a = torch.tensor([[1, 2], [3, 4]])
torch.empty_like(a)

tensor([[0, 0],
        [0, 0]])

In [14]:
probabilities = torch.tensor([100.0,100.0,100.0]) # here we define the probability of happening of each index in this case 0,1,2 all three are equally likely to occur
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 0, 1, 0, 0, 1, 2, 0, 2, 1])


In [15]:
probabilities = torch.tensor([10.0,90.0])
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [16]:
# concat
tensor = torch.tensor([1, 2, 3, 4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
torch.tril(torch.ones(5, 5))

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
torch.triu(torch.ones(5, 5))

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
out = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
print(out)
print(torch.exp(out))

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])
tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])


In [20]:
input = torch.zeros(2, 3, 4)
out = input.transpose(0, 2) # 0 is swapped with 2
out.shape

torch.Size([4, 3, 2])

In [21]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [22]:
import torch.nn as nn

sample = torch.tensor([10.0, 10.0, 10.0])
linear = nn.Linear(3, 3, bias=False) # takes n inputs and spits out 3 outputs, after applying weights 
print(linear(sample))

tensor([ 1.7672, -2.0916,  5.8658], grad_fn=<SqueezeBackward4>)


In [23]:
import torch.nn as nn

sample = torch.tensor([1.0, 2.0, 3.0])
linear = nn.Linear(3, 5, bias=False)
'''
Output 1: 1.0 * w1 + 2.0 * w2 + 3.0 * w3
Output 2: 1.0 * w4 + 2.0 * w5 + 3.0 * w6
Output 3: 1.0 * w7 + 2.0 * w8 + 3.0 * w9
Output 4: 1.0 * w10 + 2.0 * w11 + 3.0 * w12
Output 5: 1.0 * w13 + 2.0 * w14 + 3.0 * w15
'''
print(linear(sample))

tensor([-1.1904, -0.6285, -0.0477,  0.2499,  1.4173],
       grad_fn=<SqueezeBackward4>)


In [24]:
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0,2.0,3.0])

# apply softmax
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [25]:
# how softmax is working

from math import exp


total = exp(1) + exp(2) + exp(3)
print([exp(1)/total, exp(2)/total, exp(3)/total])

[0.09003057317038046, 0.24472847105479767, 0.6652409557748219]


In [26]:
# embeddings

# Initialize an embedding layer
vocab_size = 80
embedding_dim = 6
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4, 100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)
print(embedded_output)

torch.Size([4, 6])
tensor([[-0.5135,  1.0390, -1.2446, -0.0345,  1.0785,  0.0630],
        [-0.1943,  1.1602, -1.1606, -0.9859,  0.8333,  0.3026],
        [-1.2957,  0.4467,  1.3951, -0.8283,  0.7440,  2.6661],
        [-0.2011, -0.2439,  0.4974,  1.2057,  0.6495,  1.6448]],
       grad_fn=<EmbeddingBackward0>)


In [28]:
# matrix multiplication

a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [36]:
# casting

int_64 = torch.randint(100, (3, 2)).float()
#type int64
print(int_64)

float_32 = torch.rand(2,3)
#type float32
print(float_32)

print(int_64.dtype, float_32.dtype)

result = torch.matmul(int_64, float_32)
print(result)

tensor([[89., 24.],
        [21., 60.],
        [97., 76.]])
tensor([[0.6753, 0.1893, 0.1210],
        [0.3753, 0.4891, 1.0000]])
torch.float32 torch.float32
tensor([[69.1093, 28.5843, 34.7710],
        [36.7018, 33.3204, 62.5389],
        [94.0296, 55.5313, 87.7368]])


In [44]:
a = torch.rand(2, 3, 5)
print(a.shape)
print(a)
x, y, z = a.shape
a = a.view(x * y, z)
print(a.shape)
print(a)

torch.Size([2, 3, 5])
tensor([[[0.0800, 0.3569, 0.0948, 0.5243, 0.9490],
         [0.2074, 0.4757, 0.3805, 0.2216, 0.0643],
         [0.9116, 0.3358, 0.8986, 0.2214, 0.1744]],

        [[0.7819, 0.3846, 0.8480, 0.5696, 0.6885],
         [0.7043, 0.3376, 0.2023, 0.9719, 0.1213],
         [0.0708, 0.9768, 0.4784, 0.7627, 0.8062]]])
torch.Size([6, 5])
tensor([[0.0800, 0.3569, 0.0948, 0.5243, 0.9490],
        [0.2074, 0.4757, 0.3805, 0.2216, 0.0643],
        [0.9116, 0.3358, 0.8986, 0.2214, 0.1744],
        [0.7819, 0.3846, 0.8480, 0.5696, 0.6885],
        [0.7043, 0.3376, 0.2023, 0.9719, 0.1213],
        [0.0708, 0.9768, 0.4784, 0.7627, 0.8062]])


In [45]:
a = torch.rand(2, 3, 5)
print(a.shape)
print(a)
x, y, z = a.shape
a = a.view(x, y * z)
print(a.shape)
print(a)

torch.Size([2, 3, 5])
tensor([[[0.6475, 0.3445, 0.2590, 0.5563, 0.3842],
         [0.0504, 0.2160, 0.6959, 0.9777, 0.7109],
         [0.5247, 0.2178, 0.6470, 0.9346, 0.1020]],

        [[0.2335, 0.3503, 0.6501, 0.1305, 0.5181],
         [0.1311, 0.2680, 0.8721, 0.8676, 0.4088],
         [0.5977, 0.4717, 0.3604, 0.0420, 0.5911]]])
torch.Size([2, 15])
tensor([[0.6475, 0.3445, 0.2590, 0.5563, 0.3842, 0.0504, 0.2160, 0.6959, 0.9777,
         0.7109, 0.5247, 0.2178, 0.6470, 0.9346, 0.1020],
        [0.2335, 0.3503, 0.6501, 0.1305, 0.5181, 0.1311, 0.2680, 0.8721, 0.8676,
         0.4088, 0.5977, 0.4717, 0.3604, 0.0420, 0.5911]])
